// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkx-uM8ba2YtU26OKOqjdu332UmSLJDu8',
    appId: '1:997168171934:ios:9de71659439280a6d2e48f',
    messagingSenderId: '997168171934',
    projectId: 'smart-paws-auth',
    storageBucket: 'smart-paws-auth.firebasestorage.app',
    iosBundleId: 'com.example.smartpaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkx-uM8ba2YtU26OKOqjdu332UmSLJDu8',
    appId: '1:997168171934:ios:9de71659439280a6d2e48f',
    messagingSenderId: '997168171934',
    projectId: 'smart-paws-auth',
    storageBucket: 'smart-paws-auth.firebasestorage.app',
    iosBundleId: 'com.example.smartpaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBSx2dtVeNI0YHSo8LdAXsf1oJrmpoZwU',
    appId: '1:997168171934:web:942bb213a9e39332d2e48f',
    messagingSenderId: '997168171934',
    projectId: 'smart-paws-auth',
    authDomain: 'smart-paws-auth.firebaseapp.com',
    storageBucket: 'smart-paws-auth.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBSx2dtVeNI0YHSo8LdAXsf1oJrmpoZwU',
    appId: '1:997168171934:web:942bb213a9e39332d2e48f',
    messagingSenderId: '997168171934',
    projectId: 'smart-paws-auth',
    authDomain: 'smart-paws-auth.firebaseapp.com',
    storageBucket: 'smart-paws-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs32uD8H3EdNhTOBThHOrugluokGlrLwE',
    appId: '1:997168171934:android:34dfa17ff562bba3d2e48f',
    messagingSenderId: '997168171934',
    projectId: 'smart-paws-auth',
    storageBucket: 'smart-paws-auth.firebasestorage.app',
  );

}